# Generated by Django 5.2.4 on 2025-07-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmsuser',
            name='number',
            field=models.IntegerField(max_length=20, unique=True),
        ),
    ]
